# Generated by Django 3.1 on 2023-12-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_auto_20231213_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favitem',
            old_name='cart',
            new_name='fav',
        ),
    ]
